# Generated by Django 6.0.5 on 2026-05-19 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godowns', to='accounts.business')),
            ],
            options={
                'db_table': 'godowns',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces (PCS)'), ('KG', 'Kilogram (KG)'), ('MTR', 'Meter (MTR)'), ('BOX', 'Box (BOX)'), ('SET', 'Set (SET)'), ('DOZ', 'Dozen (DOZ)'), ('PAIR', 'Pair (PAIR)')], default='PCS', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gst_rate', models.DecimalField(choices=[(0.0, '0%'), (5.0, '5%'), (12.0, '12%'), (18.0, '18%'), (28.0, '28%')], decimal_places=2, default=0.0, max_digits=5)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('opening_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('low_stock_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('default_discount_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('default_discount_type', models.CharField(choices=[('percent', 'Percentage (%)'), ('flat', 'Flat Amount (₹)')], default='percent', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.business')),
                ('godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.godown')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='GodownTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('from_godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='items.godown')),
                ('to_godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='items.godown')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'db_table': 'godown_transfers',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='accounts.business')),
            ],
            options={
                'db_table': 'item_categories',
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.itemcategory'),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party')),
            ],
            options={
                'db_table': 'price_history',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('sale', 'Sale Stock Out'), ('purchase', 'Purchase Stock In'), ('sales_return', 'Sales Return In'), ('purchase_return', 'Purchase Return Out'), ('adjustment_in', 'Stock Adjustment In'), ('adjustment_out', 'Stock Adjustment Out'), ('opening', 'Opening Stock Entry'), ('transfer', 'Godown Transfer')], max_length=50)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=15)),
                ('movement_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.godown')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='items.item')),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
    ]
