# Generated by Django 6.0.5 on 2026-05-24 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('items', '0002_item_godown_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode_value', models.CharField(max_length=128)),
                ('label_size', models.CharField(default='50x25', max_length=30)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('price_source', models.CharField(choices=[('selling', 'Selling Price'), ('mrp', 'MRP'), ('none', 'No Price')], default='selling', max_length=20)),
                ('include_business_name', models.BooleanField(default=True)),
                ('include_item_name', models.BooleanField(default=True)),
                ('include_price', models.BooleanField(default=True)),
                ('include_mrp', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_labels', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_labels', to='items.item')),
            ],
            options={
                'db_table': 'barcode_labels',
                'indexes': [models.Index(fields=['business', 'item'], name='barcode_lab_busines_ae41c1_idx'), models.Index(fields=['business', 'created_at'], name='barcode_lab_busines_f243e0_idx')],
            },
        ),
    ]
