# Generated by Django 6.0.5 on 2026-05-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_custom_fields_party_prices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='itempartyprice',
            new_name='item_party__busines_861a3e_idx',
            old_name='item_party__busines_b5377b_idx',
        ),
        migrations.RenameIndex(
            model_name='itempartyprice',
            new_name='item_party__busines_1f0ff1_idx',
            old_name='item_party__busines_39810f_idx',
        ),
    ]
