# Generated by Django 6.0.5 on 2026-05-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp',
            field=models.CharField(max_length=128),
        ),
    ]
