# Generated by Django 6.0.5 on 2026-05-31 14:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otptoken_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_key', models.CharField(max_length=120)),
                ('prefix', models.CharField(max_length=80)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='accounts.business')),
            ],
            options={
                'db_table': 'document_sequences',
                'indexes': [models.Index(fields=['business', 'sequence_key'], name='doc_sequence_business_key_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'sequence_key'), name='uniq_document_sequence_per_business')],
            },
        ),
    ]
