# Generated by Django 6.0.5 on 2026-05-19 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(default='advanced_gst', max_length=30)),
                ('theme_color', models.CharField(default='#5B48F5', max_length=20)),
                ('theme_style', models.CharField(blank=True, max_length=50, null=True)),
                ('show_mrp', models.BooleanField(default=True)),
                ('show_hsn', models.BooleanField(default=True)),
                ('show_discount', models.BooleanField(default=True)),
                ('show_color', models.BooleanField(default=True)),
                ('show_cin_date', models.BooleanField(default=True)),
                ('show_grn_date', models.BooleanField(default=True)),
                ('show_free_qty', models.BooleanField(default=False)),
                ('show_party_balance', models.BooleanField(default=False)),
                ('show_item_description', models.BooleanField(default=False)),
                ('show_time_on_invoice', models.BooleanField(default=True)),
                ('show_discount_on_mrp', models.BooleanField(default=False)),
                ('paper_size', models.CharField(default='A4', max_length=10)),
                ('thermal_paper_size', models.CharField(default='2inch', max_length=10)),
                ('thermal_theme', models.CharField(default='compact', max_length=20)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('signature_url', models.TextField(blank=True, null=True)),
                ('custom_fields', models.JSONField(default=list)),
                ('invoice_prefix', models.CharField(default='CSM', max_length=20)),
                ('reset_each_year', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='accounts.business')),
            ],
            options={
                'db_table': 'invoice_settings',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(blank=True, max_length=50, null=True)),
                ('voucher_id', models.UUIDField(blank=True, null=True)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('sms', 'SMS Alert'), ('whatsapp', 'WhatsApp Alert'), ('email', 'Email Notification')], default='sms', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Scheduled'), ('sent', 'Successfully Sent'), ('failed', 'Delivery Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.business')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parties.party')),
            ],
            options={
                'db_table': 'reminders',
            },
        ),
    ]
