# Generated by Django 6.0.5 on 2026-05-24 01:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('business_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesettings',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_category', models.CharField(blank=True, default='', max_length=120)),
                ('show_in_online_store', models.BooleanField(default=False)),
                ('enable_gst_billing', models.BooleanField(default=False)),
                ('show_logo_on_invoice', models.BooleanField(default=True)),
                ('branch_billing', models.BooleanField(default=False)),
                ('show_upi_on_invoice', models.BooleanField(default=False)),
                ('print_preview', models.BooleanField(default=True)),
                ('hide_zero_stock_barcodes', models.BooleanField(default=False)),
                ('print_original_duplicate', models.BooleanField(default=True)),
                ('auto_print_after_sale', models.BooleanField(default=False)),
                ('ca_reports_enabled', models.BooleanField(default=False)),
                ('ca_name', models.CharField(blank=True, default='', max_length=120)),
                ('ca_email', models.EmailField(blank=True, default='', max_length=254)),
                ('ca_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('plan_name', models.CharField(blank=True, default='Free Plan', max_length=80)),
                ('plan_valid_till', models.DateField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, default='', max_length=40)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_preferences', to='accounts.business')),
            ],
            options={
                'db_table': 'business_preferences',
            },
        ),
        migrations.CreateModel(
            name='ReminderPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_due', models.BooleanField(default=True)),
                ('sale_invoice', models.BooleanField(default=True)),
                ('low_stock', models.BooleanField(default=False)),
                ('customer_occasions', models.BooleanField(default=False)),
                ('daily_summary', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_preferences', to='accounts.business')),
            ],
            options={
                'db_table': 'reminder_preferences',
            },
        ),
    ]
