# Generated by Django 6.0.5 on 2026-05-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('business_settings', '0002_alter_invoicesettings_invoice_prefix_and_more'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reminder',
            name='delivery_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['business', 'status', 'scheduled_at'], name='reminders_business_status_idx'),
        ),
    ]
