# Generated by Django 6.0.5 on 2026-05-28 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('business_settings', '0003_reminder_attempt_count_reminder_delivery_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('target', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='unread', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.business')),
            ],
            options={
                'db_table': 'business_notifications',
                'indexes': [models.Index(fields=['business', 'status', '-created_at'], name='notif_business_status_idx'), models.Index(fields=['business', 'source_type', 'source_id'], name='notif_business_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'source_type', 'source_id'), name='uniq_notification_source_per_business')],
            },
        ),
    ]
