# Generated by Django 6.0.5 on 2026-05-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_settings', '0004_businessnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='delivery_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reminder',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='reminder',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
