# Generated by Django 6.0.5 on 2026-06-02 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_documentsequence'),
        ('business_settings', '0005_reminder_delivery_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(max_length=40)),
                ('business_name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('activated', 'Activated'), ('rewarded', 'Rewarded'), ('expired', 'Expired')], default='invited', max_length=20)),
                ('reward_label', models.CharField(blank=True, default='Pending', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_invites', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_invites',
                'indexes': [models.Index(fields=['business', 'status', '-created_at'], name='referral_business_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'mobile'), name='uniq_referral_invite_mobile_per_business')],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('billing', 'Billing'), ('reports', 'Reports'), ('subscription', 'Subscription'), ('technical', 'Technical'), ('account', 'Account')], default='billing', max_length=20)),
                ('channel', models.CharField(choices=[('chat', 'Chat'), ('call', 'Call'), ('email', 'Email')], default='chat', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('message', models.TextField()),
                ('contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('contact_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_tickets',
                'indexes': [models.Index(fields=['business', 'status', '-created_at'], name='support_business_status_idx')],
                'unique_together': {('business', 'ticket_number')},
            },
        ),
    ]
