# Generated by Django 6.0.5 on 2026-05-28 08:57

import apps.accounting.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.CharField(max_length=80)),
                ('report_name', models.CharField(max_length=180)),
                ('recipient', models.CharField(max_length=180)),
                ('date_range', models.CharField(blank=True, default='', max_length=80)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('sent', 'Sent'), ('failed', 'Failed')], default='prepared', max_length=20)),
                ('share_token', models.CharField(default=apps.accounting.models.report_share_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_shares', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_shares',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'report_id', 'created_at'], name='report_shar_busines_fc0bab_idx'), models.Index(fields=['business', 'recipient', 'created_at'], name='report_shar_busines_b40b3e_idx')],
            },
        ),
    ]
