# Generated by Django 6.0.5 on 2026-05-24 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


DEFAULT_SMS_TEMPLATES = [
    (
        "Festival Sale",
        "offer",
        "CSM SILKS festival offer is live. Visit our store for fresh silk saree collections and special customer pricing.",
    ),
    (
        "New Saree Arrivals",
        "new_arrival",
        "New silk saree arrivals are available at CSM SILKS today. Reply or visit the store to see the latest designs.",
    ),
    (
        "Payment Reminder",
        "payment",
        "Dear customer, your CSM SILKS account has a pending balance. Please clear the payment at your convenience.",
    ),
    (
        "Store Update",
        "store",
        "CSM SILKS online catalog is updated. Contact us to reserve sarees or visit the showroom for assistance.",
    ),
]


def seed_sms_marketing(apps, schema_editor):
    Business = apps.get_model("accounts", "Business")
    SMSTemplate = apps.get_model("business_tools", "SMSTemplate")
    SMSCreditLedger = apps.get_model("business_tools", "SMSCreditLedger")

    for business in Business.objects.all():
        for name, category, message in DEFAULT_SMS_TEMPLATES:
            SMSTemplate.objects.get_or_create(
                business=business,
                name=name,
                defaults={"category": category, "message": message, "is_active": True},
            )

        SMSCreditLedger.objects.get_or_create(
            business=business,
            reference="OPENING-SMS-CREDITS",
            defaults={
                "entry_type": "credit",
                "credits": 500,
                "notes": "Opening SMS credit balance for tenant marketing workspace.",
            },
        )


def unseed_sms_marketing(apps, schema_editor):
    Business = apps.get_model("accounts", "Business")
    SMSTemplate = apps.get_model("business_tools", "SMSTemplate")
    SMSCreditLedger = apps.get_model("business_tools", "SMSCreditLedger")

    template_names = [name for name, _, _ in DEFAULT_SMS_TEMPLATES]
    for business in Business.objects.all():
        SMSTemplate.objects.filter(business=business, name__in=template_names).delete()
        SMSCreditLedger.objects.filter(business=business, reference="OPENING-SMS-CREDITS").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('business_tools', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('offer', 'Offer'), ('new_arrival', 'New Arrival'), ('payment', 'Payment'), ('store', 'Store Update')], default='offer', max_length=30)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='accounts.business')),
            ],
            options={
                'db_table': 'sms_templates',
            },
        ),
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_number', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=160)),
                ('audience', models.CharField(choices=[('all_customers', 'All Customers'), ('manual', 'Selected Customers')], default='all_customers', max_length=30)),
                ('message', models.TextField()),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('credit_cost', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_campaigns', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='business_tools.smstemplate')),
            ],
            options={
                'db_table': 'sms_campaigns',
            },
        ),
        migrations.CreateModel(
            name='SMSCreditLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('credits', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_credit_ledger', to='accounts.business')),
            ],
            options={
                'db_table': 'sms_credit_ledger',
                'indexes': [models.Index(fields=['business', 'created_at'], name='sms_credit_busines_a80572_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_recipients', to='accounts.business')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='business_tools.smscampaign')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_recipients', to='parties.party')),
            ],
            options={
                'db_table': 'sms_recipients',
                'indexes': [models.Index(fields=['business', 'status'], name='sms_recipi_busines_7dfb31_idx')],
                'unique_together': {('campaign', 'mobile')},
            },
        ),
        migrations.AddIndex(
            model_name='smstemplate',
            index=models.Index(fields=['business', 'category'], name='sms_templa_busines_5f7d1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='smstemplate',
            unique_together={('business', 'name')},
        ),
        migrations.AddIndex(
            model_name='smscampaign',
            index=models.Index(fields=['business', 'status', 'created_at'], name='sms_campai_busines_83df21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='smscampaign',
            unique_together={('business', 'campaign_number')},
        ),
        migrations.RunPython(seed_sms_marketing, unseed_sms_marketing),
    ]
