# Generated by Django 6.0.5 on 2026-05-31 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otptoken_otp'),
        ('business_tools', '0002_smstemplate_smscampaign_smscreditledger_smsrecipient_and_more'),
        ('items', '0005_rename_item_party__busines_b5377b_idx_item_party__busines_861a3e_idx_and_more'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='delivery_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shipping_label_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shipping_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shipping_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shipping_status',
            field=models.CharField(choices=[('not_created', 'Not Created'), ('order_created', 'Order Created'), ('awb_assigned', 'AWB Assigned'), ('pickup_scheduled', 'Pickup Scheduled'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='not_created', max_length=30),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shiprocket_awb_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shiprocket_courier_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shiprocket_shipment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='tracking_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='tracking_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['business', 'shipping_status'], name='online_order_shipping_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['business', 'shiprocket_awb_code'], name='online_order_awb_idx'),
        ),
    ]
