# Generated by Django 6.0.5 on 2026-05-31 05:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otptoken_otp'),
        ('business_tools', '0004_smsrecipient_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingDeliveryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('provider_status', models.CharField(blank=True, default='', max_length=80)),
                ('normalized_status', models.CharField(blank=True, default='', max_length=20)),
                ('target_type', models.CharField(choices=[('sms_recipient', 'SMS Recipient'), ('reminder', 'Reminder'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='processed', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_events', to='accounts.business')),
            ],
            options={
                'db_table': 'messaging_delivery_events',
                'indexes': [models.Index(fields=['provider', 'provider_message_id'], name='msg_event_provider_msg_idx'), models.Index(fields=['business', '-created_at'], name='msg_event_business_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_msg_event_provider_id')],
            },
        ),
    ]
