# Generated by Django 6.0.5 on 2026-05-19 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('parties', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=50)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account Transfer'), ('upi', 'UPI (GPay/PhonePe/etc.)'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_id', models.UUIDField(blank=True, null=True)),
                ('is_advance', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_in', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_in', to='parties.party')),
            ],
            options={
                'db_table': 'payments_in',
            },
        ),
        migrations.CreateModel(
            name='PaymentInSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settled_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='sales.salesinvoice')),
                ('payment_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='payments.paymentin')),
            ],
            options={
                'db_table': 'payment_in_settlements',
            },
        ),
        migrations.CreateModel(
            name='PaymentOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=50)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_id', models.UUIDField(blank=True, null=True)),
                ('is_advance', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_out', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_out', to='parties.party')),
            ],
            options={
                'db_table': 'payments_out',
            },
        ),
        migrations.CreateModel(
            name='PaymentOutSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settled_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='purchases.purchaseinvoice')),
                ('payment_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='payments.paymentout')),
            ],
            options={
                'db_table': 'payment_out_settlements',
            },
        ),
    ]
