# Generated by Django 6.0.5 on 2026-05-28 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('parties', '0001_initial'),
        ('payments', '0002_payment_void_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentin',
            constraint=models.UniqueConstraint(fields=('business', 'payment_number'), name='uniq_payment_in_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='paymentout',
            constraint=models.UniqueConstraint(fields=('business', 'payment_number'), name='uniq_payment_out_number_per_business'),
        ),
    ]
