# Generated by Django 6.0.5 on 2026-05-31 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otptoken_otp'),
        ('parties', '0001_initial'),
        ('payments', '0003_paymentin_uniq_payment_in_number_per_business_and_more'),
        ('sales', '0003_einvoice_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='razorpay', max_length=50)),
                ('provider_order_id', models.CharField(max_length=100, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_status', models.CharField(blank=True, default='', max_length=50)),
                ('receipt', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_subunits', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('attempted', 'Attempted'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('signature_verified', models.BooleanField(default=False)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway_orders', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_gateway_orders', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_gateway_orders', to='sales.salesinvoice')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_gateway_orders', to='parties.party')),
                ('payment_in', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_order', to='payments.paymentin')),
            ],
            options={
                'db_table': 'payment_gateway_orders',
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='razorpay', max_length=50)),
                ('event_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='processed', max_length=20)),
                ('signature_valid', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_gateway_events', to='accounts.business')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_events', to='payments.paymentgatewayorder')),
            ],
            options={
                'db_table': 'payment_gateway_events',
            },
        ),
        migrations.AddIndex(
            model_name='paymentgatewayorder',
            index=models.Index(fields=['business', 'status'], name='pg_order_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewayorder',
            index=models.Index(fields=['provider', 'provider_order_id'], name='pg_order_provider_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentgatewayorder',
            constraint=models.UniqueConstraint(fields=('business', 'receipt'), name='uniq_gateway_order_receipt_per_business'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewayevent',
            index=models.Index(fields=['business', 'created_at'], name='pg_event_biz_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewayevent',
            index=models.Index(fields=['provider', 'event_type'], name='pg_event_provider_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentgatewayevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_gateway_event_per_provider'),
        ),
    ]
