# Generated by Django 6.0.5 on 2026-05-30 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otptoken_otp'),
        ('items', '0005_rename_item_party__busines_b5377b_idx_item_party__busines_861a3e_idx_and_more'),
        ('parties', '0001_initial'),
        ('purchases', '0002_alter_purchaseinvoice_invoice_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('adjusted', 'Adjusted'), ('pending_adjustment', 'Pending Adjustment'), ('cancelled', 'Cancelled')], default='adjusted', max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='purchases.purchaseinvoice')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='parties.party')),
            ],
            options={
                'db_table': 'purchase_returns',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sort_order', models.IntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchases.purchasereturn')),
            ],
            options={
                'db_table': 'purchase_return_items',
            },
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['business', 'return_date'], name='purchase_re_busines_3f1a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['business', 'status'], name='purchase_re_busines_983f84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasereturn',
            unique_together={('business', 'return_number')},
        ),
    ]
